### PR TITLE
bug fix in reset slice

### PR DESCRIPTION
**Pull request by zcolleen**
Hi! We are using your plugin and its working really great, but recently we have discovered one little bug about memory pooling, connected with this issue https://github.com/planetscale/vtprotobuf/issues/8 . When the message contains repeated field you just reduse size  to zero when ResetVT not to overload GC and its cool. The problem is that if repeated element contains pointer field or other repeated field, firstly when you unmarshall data to it and these fields are present in request, fields will be filled in. Secondly, when another request comes without pointer field or slice in element, you take element from pool with this fields set, unmarshal data to it, and then you have a kind of merged data from previous request. Thats why we thought that it may be good to reduse size  to zero not only at top level slice, but on lower levels too, and we came with pr as one of the options to solve this issue without overhead of complexity. I hope that i could explain everything clearly. Waiting very much for your feedback

### CODE REVIEW

**Comment by zcolleen** [comment]
@vmg hi! Unfortunately my solution did not pass conformance tests so i had to go other way. I have added  test proto files and some test cases to demonstrate the bug. Please pay attention how ResetVT is generated for Test1 and Test2, they are created in different way. You can recreate the bug by commenting my solution and running test cases. First test case will always pass as reducing size of slice is working with primitive types in repeated field but second case will fail as repeated filed is not of primitive type.

**Comment by vmg** [comment]
Alright! I pushed some CI changes to allow the tests to actually run in production, but overall this is looking very good. Thanks for spotting the bug and taking the time to fix it.

**Comment by zcolleen** [comment]
Thank you

**Comment by npordash** [comment]
Hi @zcolleen @vmg 

I'm a little confused about the outcome of this PR and was hoping someone could clarify my observations.

Given the following example proto:

```proto
message Response {
	repeated Data data = 1;
}

message Data {
	// some fields here
}
```

Prior to this PR I'd see code generated as such:
```go
func (m *Response) ResetVT() {
	for _, mm := range m.Data {
		mm.ResetVT()
	}
	f0 := m.Data[:0]
	m.Reset()
	m.Data = f0
}
```

After this PR I see the following:
```go
func (m *Response) ResetVT() {
	for _, mm := range m.Data {
		mm.ResetVT()
	}
	m.Reset()
}
```

This seems like it defeats the entire purpose of pooling and we're also doing extra work calling `ResetVT` on things that are going to become unaddressable and get garbage collected anyways.

I didn't quite understand the bug this PR was originally trying to solve. In reality I have cases where there are pooled repeated fields up to 3 levels deep and `ResetVT()` is being called correctly everywhere prior to resizing the slice to 0. Since `ResetVT()` eventually calls `Reset()` which replaces the struct with a zero-value one I am not sure how we can end up in a situation with merged data from a previous unmarshalling.

**Comment by npordash** [comment]
Hi @zcolleen @vmg 

I'm a little confused about the outcome of this PR and was hoping someone could clarify my observations.

Given the following example proto:

```proto
message Response {
	repeated Data data = 1;
}

message Data {
	// some fields here
}
```

Prior to this PR I'd see code generated as such:
```go
func (m *Response) ResetVT() {
	for _, mm := range m.Data {
		mm.ResetVT()
	}
	f0 := m.Data[:0]
	m.Reset()
	m.Data = f0
}
```

After this PR I see the following:
```go
func (m *Response) ResetVT() {
	for _, mm := range m.Data {
		mm.ResetVT()
	}
	m.Reset()
}
```

This seems like it defeats the entire purpose of pooling and we're also doing extra work calling `ResetVT` on things that are going to become unaddressable and get garbage collected anyways.

I didn't quite understand the bug this PR was originally trying to solve. In reality I have cases where there are pooled repeated fields up to 3 levels deep and `ResetVT()` is being called correctly everywhere prior to resizing the slice to 0. Since `ResetVT()` eventually calls `Reset()` which replaces the struct with a zero-value one I am not sure how we can end up in a situation with merged data from a previous unmarshalling.

**Comment by zcolleen** [comment]
@npordash hi! I have added some test cases to demonstrate this bug, have you tried them on new and on old versions to see the difference?

**Comment by cyriltovena** [comment]
@vmg Where you able to understand the bug ? I have doubt there was a bug here. 

I can understand that if you pool a child object and ResetVT then you're in trouble. But that's more a usage issue.

I'd love to understand more about this please ?

**Comment by zcolleen** [comment]
@cyriltovena hi! It actually easy to reproduce this bug, just go to pool_with_slice_reuse_vtproto.pb.go and put ResetVT this way 
`func (m *Test2) ResetVT() {
	f0 := m.Sl[:0]
	m.Reset()
	m.Sl = f0
}`
to make it behave as before. 
Then run Test_Pool_slice_recreation test and you will see the bug as the test will fail. Why it is so? Because when you increase length of slice Sl while unmarshalling, you make available previous value in Slice2 and if you are not refilling fields of Slice2[0], they remain with the previous values. I hope i could explain this more clearly but the best way to understand this is just to make this test fail. This thing is really hard to understand.
Also i made this small example to demonstrate what is the bug about

`var pool = sync.Pool{New: func() any {
	return &MainStruct{}
}}

type MainStruct struct {
	SomeSliceWithPointers []*SomeStruct
}

type SomeStruct struct {
	A int
	B int
}

func main() {
	example1 := &MainStruct{SomeSliceWithPointers: []*SomeStruct{{A: 1, B: 2}}}

	// ResetVT
	example1.SomeSliceWithPointers = example1.SomeSliceWithPointers[:0]
	pool.Put(example1)

	example2 := pool.Get().(*MainStruct)
	example2.SomeSliceWithPointers = example2.SomeSliceWithPointers[:1]

	example2.SomeSliceWithPointers[0].A = 10

	// A == 10 because we overwritten this field BUT we still got example2.SomeSliceWithPointers[0].B == 2 from the previous request
	// and we expected it to be default value 0
	fmt.Println(example2.SomeSliceWithPointers[0])
}
`

**Comment by npordash** [comment]
@zcolleen I don't think your example is correct, because `ResetVT` should also be called on `SomeStruct` which would zero out the fields.

What would actually happen prior to this PR is:
```go
func (m *MainStruct) ResetVT() {
    for _, mm := range m.SomeSliceWithPointers {
        mm.ResetVT() // resetting *SomeStruct
    }
    f0 := m.SomeSliceWithPointers[:0]
    m.Reset()
    m.SomeSliceWithPointers = f0
}
```

**Comment by cyriltovena** [comment]
Ok I see the problem, this is for zero value they are not zeroed back again why don't we reset each value instead  ?

```
func (m *Test2) ResetVT() {
	for _, e := range m.Sl {
		e.Reset() // This should be ResetVT though
	}
	f0 := m.Sl[:0]
	m.Reset()
	m.Sl = f0
}
```

**Comment by cyriltovena** [comment]
Definitively agree with you @npordash. But in the test `ResetVT` doesn't exist for Sl I wonder why ?

**Comment by cyriltovena** [comment]
I think I see now.  The fix is to never re-use slice on struct member that are not poolable.

**Comment by zcolleen** [comment]
@npordash your sample would work as expected, but if you put back previous behavior you will see that it is only generated like this

**Comment by zcolleen** [comment]
may be we could add something like this https://github.com/planetscale/vtprotobuf/compare/main...zcolleen:vtprotobuf:main so if struct member is poolable too, we could go to previous behaviour but have to test this

**Comment by cyriltovena** [comment]
I have something close where I still reuse, but correctly reset it. This is for your special edge case, where you have a mix of pool and non pool feature. I suggest you make every children poolable for better result.

**Comment by zcolleen** [comment]
yes, i think your approach is better

**Pull request merged**
