### PR TITLE
grpc.Codec: Implement fallback to proto.Message

### PR DESCRIPTION
**Pull request by terwey**
Implement a fallback to proto.Message, this is required if you're using the grpc-gateway.

### CODE REVIEW

**Comment by epk** [comment]
Hi @vmg, this would be nice to have, I am not sure of the performance implications of it though

**Comment by terwey** [comment]
Hey,

that's fair that we need some comparison numbers.

Locally took the current vtprotobuf Codec and compared it to the patched version in a Benchmark.

I created a small Protobuf message which I used for the Benchmark.

```
message Benchmark {
  string name = 1;
  google.protobuf.Timestamp created = 2;
}
```

The import I had for the fallback Codec (in the PR) is not public so I just changed the import on the Gist:
https://gist.github.com/terwey/c1f716446f74803ba35eef5722acd729

The Benchmark has been executed with: 
```
/usr/local/go/bin/go test -benchmem -run=^$ -bench ^(Benchmark_MarshalFallback|Benchmark_MarshalOriginal|Benchmark_UnmarshalFallback|Benchmark_UnmarshalOriginal)$ foo/fallback -count 10 -v -benchtime 10s -cpu 4 -timeout 30m
```

benchstat overview

```
name                  time/op
_MarshalFallback-4    403ns ± 5%
_MarshalOriginal-4    410ns ±10%
_UnmarshalFallback-4  265ns ± 6%
_UnmarshalOriginal-4  263ns ± 7%

name                  alloc/op
_MarshalFallback-4    40.0B ± 0%
_MarshalOriginal-4    40.0B ± 0%
_UnmarshalFallback-4  3.00B ± 0%
_UnmarshalOriginal-4  3.00B ± 0%

name                  allocs/op
_MarshalFallback-4     2.00 ± 0%
_MarshalOriginal-4     2.00 ± 0%
_UnmarshalFallback-4   1.00 ± 0%
_UnmarshalOriginal-4   1.00 ± 0%
```

The raw result is here: https://gist.github.com/terwey/1f3cf85b46f62a3f80268a9d3be14396

**Comment by vmg** [comment]
Hey! Thanks for the contribution and for the benchmarks. In case you missed, this functionality is already required and used by Vitess, but I implemented it as a custom codec that lives in Vitess:

https://github.com/vitessio/vitess/blob/main/go/vt/servenv/grpc_codec.go

The reason why I left it on a separate codec is because, depending on the project, it may want to use a different version of the Go ProtoBuf library (either v1 or v2) to perform the `proto.Message` test.

I am not concerned with the performance of the extra assertion, but I don't want to add the dependency on a `protobuf` package to the codec. I think it's much easier if you add your own codec that suits your needs to your project, just like I did for Vitess.

Cheers!

**Comment by terwey** [comment]
@vmg fair point, I would recommend however adding a small note about it to the README that this can/should be done when using e.g. the gRPC Gateway.

**Comment by vmg** [comment]
Good idea! I'll do that right away.

**Pull request closed without merging**
