### PR TITLE
generator: support proto2

### LINKED ISSUE #11: Proto2 Support
Is it expected that the vtproto files aren't currently being generated for proto2 files or do I have something misconfigured?

### PR DESCRIPTION
**Pull request by euroelessar**
Proto2 support, it passes conformance tests and on the first glance doesn't miss any functionality.

Fixes #11.

### CODE REVIEW

**Comment by euroelessar** [comment]
Unfortunately I had to also implement group support, didn't find a reasonable way to avoid it while preserving passing conformance tests.

**Comment by euroelessar** [comment]
@vmg Can you have a look, please?

**Comment by vmg** [comment]
This looks very good to me. There are no changes on the generate proto3 code, which I think was the critical goal for this PR, and the generated proto2 code looks reasonable to me (at the very least it passes the conformance suite). I'm gonna merge this, although potential users beware that I won't be testing the proto2 codegen in Vitess because we don't have any proto2 in Vitess!

**Comment by vmg** [comment]
Thanks for the contribution!

**Pull request merged**
